baseurl = "https://nicewook.github.io/blog/"
languageCode = "en-us"
title = "JustHS"
theme = "hugo-steam-theme"
publishDir = "docs"

relativeURLs = "true"
uglyURLs = "true"
canonifyURLs = "true"  # changes to absolute URLs

disqusShortname = "nicewook-github-io"
paginate = 10

[params]

	title = "JustHS"
	subtitle = "software development"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themeColor = "blue"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = ""

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Jeong Hyunseok"
	bio = ""
	description = "JustHS blog"
	location = "" # optional
	twitter = "" # optional
	github = "" # optional
 	gitlab = "" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs. 
	comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"